[package]
name = "pixt"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Terminal Based Cross Platform Image Viewer"
repository = "https://github.com/BiswajitThakur/pixt"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
crossterm = "0.28.1"
image = "0.25.5"
