name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history for branch switching

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build project
        run: |
          wasm-pack build --target web --release

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          cp -r index.html style.css pkg deploy/
          # Copy any other static files (like images, JS)
          [ -d "static" ] && cp -r static deploy/

      - name: Deploy to gh-pages branch
        run: |
          # Create temporary clone of gh-pages
          git fetch origin gh-pages || true
          git switch gh-pages || git checkout --orphan gh-pages

          # Remove old files
          rm -rf ./*

          # Copy new site files
          cp -r ../deploy/* ./

          # Commit and push
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update site from main" || echo "No changes to commit"
          git push origin gh-pages --force
